### ISSUE TITLE
Plan a standalone web app for individual users

### ISSUE THREAD

**Issue by wolfborg** [wolfborg/Kanji2000-Website#13]
As the site is currently designed, there really isn't a need to even use a local web server with database setup for this. There is no online features or ways to interact with each other, so why bother with all that and user login setups? Originally this was made for a website development class project while I was in college, so we had to showcase our database knowledge with this. Now, it doesn't have to, so I'll probably save how it currently is in a separate branch for future reference while designing a rework for the standalone web app.

**Comment by wolfborg** [comment]
As it stands right now, the website has the following three pages:

index.php - The front page
![image](https://user-images.githubusercontent.com/9553466/80168482-f6d34280-85b0-11ea-88f5-28fda70857fc.png)
Used to inform new users and to register or login. Most of the login stuff can be scrapped, but letting the users set their own display name could be cool.

dashboard.php - The dashboard page
![image](https://user-images.githubusercontent.com/9553466/80168733-9e507500-85b1-11ea-8ff9-aa5f45a165b4.png)
Used to display the current user's information and has a start quiz button. Also includes an account dropdown menu that has options to change your account settings or logout. A future plan for this page was to also display a random daily kanji. For the restructure, we can remove the logout button and rework the settings into a part of this page itself, so they can structure the quiz to the parameters they want.

quiz.php - The quiz page
![image](https://user-images.githubusercontent.com/9553466/80168901-174fcc80-85b2-11ea-9ad4-9c54c1be228b.png)
Used to quiz the user with a random Japanese kanji and four English answers randomly placed, one of which is correct and the others are random. If they get it right, the English button turns green and then it goes to the next kanji. If they get it wrong, the button turns red but they can keep trying answers until they find the correct one. If they get three wrong, the last one, which will be the correct one, is highlighted green and then it moves on to the next kanji. There might be better ways to set this up for better education in the future, but that can be a different task in the future.

So the first step would probably be to design some mock-ups of how the rework should look and descriptions of how they should work functionally.

I also want to use this opportunity to brush up on my React knowledge, so we'll use that. Probably makes local installs easier for people who want to contribute anyways.

Tasks for this right now include:
- [ ] Breakdown of necessary and additional features #14 
- [ ] Mock-ups of Home, Dashboard, and Quiz pages #15
- [ ] Descriptions of mock-up functionality #16
- [ ] Setup React base project #17
- [ ] Implement HTML data onto pages #18
- [ ] Apply mock-up layout and theme #19
- [ ] Integrate functionality to the site #20
- [ ] Test and log any issues #21 
- [ ] Fix issues and test again #22 
- [ ] Repeat debug process until complete #23 

These tasks will each have their own separate issues.

All in all, working on this again is gonna be fun.
